# Starship prompt configuration
# Replaces oh-my-posh with better Nushell integration

format = """
[╭─](bold green)$username[@](bold yellow)$hostname in $directory$git_branch$git_status
[╰─](bold green)$character"""

# Character changes based on vi mode
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"  # Normal mode in vi

[username]
format = "[$user]($style)"
style_user = "bold cyan"
show_always = true

[hostname]
format = "[$hostname]($style)"
style = "bold blue"
ssh_only = false

[directory]
style = "bold magenta"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = " on [$symbol$branch]($style)"
symbol = " "
style = "bold purple"

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style))"
style = "bold yellow"

[nodejs]
format = " via [$symbol($version )]($style)"
symbol = " "
style = "bold green"

[python]
format = " via [$symbol$pyenv_prefix($version )]($style)"
symbol = " "
style = "bold yellow"
pyenv_version_name = true

[docker_context]
format = " via [$symbol$context]($style)"
symbol = " "
style = "bold blue"

[cmd_duration]
min_time = 500
format = " took [$duration]($style)"
style = "bold yellow"
